name: Label issues

# Controls when the workflow will run
on:
  issues:
    types:
      - reopen
      - opened
jobs:
  label_issues:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label Issues
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "Needs more refinement"
          repo-token: ${{ secrets.GITHUB_TOKEN}}
